# Generated by Django 4.1.10 on 2023-09-23 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('kid_age', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='challenges/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.category')),
                ('content', models.ManyToManyField(to='Api.content')),
            ],
        ),
    ]
